<Project>
  <ItemGroup>
    <PackageVersion Include="FluentValidation" Version="11.9.0" />
    <PackageVersion Include="FluentAssertions" Version="8.8.0" />
    <PackageVersion Include="MemoryPack" Version="1.21.4" />
    <PackageVersion Include="Microsoft.Bcl.Memory" Version="10.0.0" />
    <PackageVersion Include="Nivaes.Extensions" Version="2.2.34" />
    <PackageVersion Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageVersion Condition="'$(TargetFramework)' == 'net8.0' OR '$(TargetFramework)' == 'net9.0' " Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.11" />
    <PackageVersion Condition="'$(TargetFramework)' == 'net10.0'" Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0" />
    <PackageVersion Condition="'$(TargetFramework)' == 'net8.0' OR '$(TargetFramework)' == 'net9.0' " Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageVersion Condition="'$(TargetFramework)' == 'net10.0' " Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Nivaes.DataTestGenerator.XUnit" Version="2.11.20" />
    <PackageVersion Include="Verify.SourceGenerators" Version="2.5.0" />
    <PackageVersion Include="Verify.Xunit" Version="31.8.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.14.1" />
    <PackageVersion Include="AsyncFixer" Version="1.6.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.100" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.15.0.120848" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
  </ItemGroup>
</Project>
