<Project>

  <PropertyGroup Condition="$(MSBuildProjectName.Contains('Test')) == 'False'">
    <Copyright>Copyright (c) Nivaes Systems</Copyright>
    <PackageProject>https://github.com/Nivaes</PackageProject>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <Authors>Nivaes Systems</Authors>
    <Company>Nivaes Systems</Company>
    <Owners>Nivaes</Owners>
    <PackageReleaseNotes>https://www.nivaes.com</PackageReleaseNotes>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/Nivaes/Nivaes.Shared</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Product>$(AssemblyName) ($(TargetFramework))</Product>
  </PropertyGroup>
  
  <PropertyGroup>
    <NeutralLanguage>en</NeutralLanguage>
    <Version>1.0.17</Version>
  </PropertyGroup>
  
  <PropertyGroup>
    <RepoRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</RepoRoot>
    <BaseOutputPath>$(RepoRoot)Artifacts\$(Configuration)\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RepoRoot)Artifacts\$(Configuration)\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>

    <LangVersion>latest</LangVersion>
    <!--<NoWarn>$(NoWarn);1591;1701;1702;1705;VSX1000</NoWarn>-->

    <IsTestProject>$(MSBuildProjectName.Contains('Test'))</IsTestProject>
    
    <GenerateDocumentationFile Condition=" '$(Configuration)' == 'Release' ">true</GenerateDocumentationFile>
    <GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' and '$(IsTestProject)' != 'true'">true</GeneratePackageOnBuild>

    <!--<Platform>AnyCPU</Platform>
    <DebugType>full</DebugType>-->
   
  </PropertyGroup>
  
</Project>
