<Project>

  <PropertyGroup Condition="$(MSBuildProjectName.Contains('Test')) == 'False'">
    <Copyright>Copyright (c) Nivaes Systems</Copyright>
    <PackageProject>https://github.com/Nivaes</PackageProject>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <Authors>Nivaes Systems</Authors>
    <Company>Nivaes Systems</Company>
    <Owners>Nivaes</Owners>
    <PackageReleaseNotes>https://www.nivaes.com</PackageReleaseNotes>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/Nivaes/Nivaes.App.Shared</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Product>$(AssemblyName) ($(TargetFramework))</Product>
  </PropertyGroup>
  
  <PropertyGroup>
    <NeutralLanguage>en</NeutralLanguage>
    <Version>0.0.0-dev</Version>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>

  <PropertyGroup>
    <SolutionDirPath Condition=" '$(SolutionDir)' != '' ">$(SolutionDir)ArtifactsVS\</SolutionDirPath>
    <SolutionDirPath Condition=" '$(SolutionDir)' == '' ">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))Artifacts\</SolutionDirPath>

    <!--Output paths-->
    <BaseIntermediateOutputPath>$(SolutionDirPath)obj\$(Configuration)\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(SolutionDirPath)obj\$(Configuration)\$(MSBuildProjectName)\</IntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(IntermediateOutputPath)\</MSBuildProjectExtensionsPath>
    <OutputPath>$(SolutionDirPath)bin\$(MSBuildProjectName)\</OutputPath>
    <DocumentationFile>$(SolutionDirPath)doc\$(Configuration)\$(MSBuildProjectName).xml</DocumentationFile>
  </PropertyGroup>


  <PropertyGroup>
    <IsTestProject>$(MSBuildProjectName.Contains('UnitTest'))</IsTestProject>
    
    <!--<GenerateDocumentationFile Condition=" '$(Configuration)' == 'Release' ">true</GenerateDocumentationFile>-->
    <GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' and '$(IsTestProject)' != 'true'">true</GeneratePackageOnBuild>
   
  </PropertyGroup>

</Project>
