<Project>

  <ItemGroup>
    <PackageReference Update="FluentValidation" Version="10.3.4" />
    <PackageReference Update="FluentAssertions" Version="6.2.0" />

    <PackageReference Update="Nivaes.Async" Version="1.4.17" />

    <PackageReference Update="protobuf-net.Grpc" Version="1.0.152" />
    <PackageReference Update="protobuf-net.BuildTools" Version="3.0.101"/>

    <PackageReference Update="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Update="System.Threading.Tasks.Extensions" Version="4.5.4" />

    <PackageReference Update="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.11" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Update="Moq" Version="4.16.1" />
    <PackageReference Update="Nivaes.DataTestGenerator.XUnit" Version="2.7.8" />
    <PackageReference Update="xunit" Version="2.4.1" />
  </ItemGroup>
  
</Project>
