<Project>

  <ItemGroup>
    <PackageReference Update="FluentValidation" Version="10.0.1" />
    <PackageReference Update="FluentAssertions" Version="5.10.3" />

    <PackageReference Update="Nivaes.Async" Version="1.4.17" />

    <PackageReference Update="protobuf-net.Grpc" Version="1.0.152" />
    <PackageReference Update="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Update="System.Threading.Tasks.Extensions" Version="4.5.4" />

    <PackageReference Update="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.4" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.4" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Update="Moq" Version="4.16.1" />
    <PackageReference Update="Nivaes.DataTestGenerator.XUnit" Version="2.7.8" />
    <PackageReference Update="xunit" Version="2.4.1" />
  </ItemGroup>
  
</Project>
