<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>

    <AssemblyName>Nivaes.App.Shared</AssemblyName>
    <RootNamespace>Nivaes.App</RootNamespace>

    <RunAOTAnalysis>true</RunAOTAnalysis>
    <IsAotCompatible>true</IsAotCompatible>

    <!--<PublishAot>true</PublishAot>-->

  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Nivaes.App.Shared</PackageId>
    <Title>Nivaes App Shared</Title>

    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <Product>Nivaes App shared</Product>
    <Description>Nivaes App shared.</Description>
    <PackageTags>Nivaes;App</PackageTags>

    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LightProto" />
    <PackageReference Include="MemoryPack" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Nivaes.Extensions" />
    <ProjectReference Include="..\Nivaes.App.SourceGenerator\Nivaes.App.SourceGenerator.csproj">
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>true</ReferenceOutputAssembly>

      <PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
      <IncludeAssets>analyzers</IncludeAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nivaes.App.Shared.UnitTest" />
    <InternalsVisibleTo Include="Nivaes.App.SourceGenerator.UnitTest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Components\Exception\LocationString\ConnectionExceptionLocalizationString.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConnectionExceptionLocalizationString.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Components\Exception\LocationString\ConnectionExceptionLocalizationString.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ConnectionExceptionLocalizationString.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Nivaes</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Update="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
