<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>

    <AssemblyName>Nivaes.App.Shared</AssemblyName>
    <RootNamespace>Nivaes.App</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Nivaes.App.Shared</PackageId>
    <Title>Nivaes App Shared</Title>

    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <Product>Nivaes App shared</Product>
    <Description>Nivaes App shared.</Description>
    <PackageTags>Nivaes;App</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Nivaes.Tools" />

    <PackageReference Include="protobuf-net.BuildTools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="protobuf-net.Grpc" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />

    <ProjectReference Include="..\..\Sources\Nivaes.App.Compilers.Toolset\Nivaes.App.Compilers.Toolset.csproj" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Components\Exception\LocationString\ConnectionExceptionLocalizationString.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConnectionExceptionLocalizationString.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Update="Components\Exception\LocationString\ConnectionExceptionLocalizationString.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ConnectionExceptionLocalizationString.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Nivaes</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
</Project>
