<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net5.0</TargetFrameworks>

    <AssemblyName>Nivaes.App.Shared</AssemblyName>
    <RootNamespace>Nivaes.App</RootNamespace>
    
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Nivaes.App.Shared</PackageId>
    <Title>Nivaes App Shared</Title>

    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <Product>Nivaes App shared</Product>
    <Description>Nivaes App shared.</Description>
    <PackageTags>Nivaes;App</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="9.2.2" />
    <PackageReference Include="Nivaes.Async" Version="1.3.14" />
    <PackageReference Include="protobuf-net.Grpc" Version="1.0.123" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.7.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Components\Exception\LocationString\ConnectionExceptionLocalizationString.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConnectionExceptionLocalizationString.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Update="Components\Exception\LocationString\ConnectionExceptionLocalizationString.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ConnectionExceptionLocalizationString.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Nivaes</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
  
</Project>
