<Project>
  
  <PropertyGroup>
    <Copyright>Copyright (c) Nivaes Systems</Copyright>
    <PackageProject>https://github.com/Nivaes</PackageProject>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <Authors>Nivaes Systems</Authors>
    <Company>Nivaes Systems</Company>
    <Owners>Nivaes</Owners>
    <PackageReleaseNotes>https://www.nivaes.com</PackageReleaseNotes>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/Nivaes/Nivaes.Shared</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Product>$(AssemblyName) ($(TargetFramework))</Product>
    <!--<NeutralLanguage>en</NeutralLanguage>
    <Version>1.0.9</Version>-->
  </PropertyGroup>

  <PropertyGroup>
    <RepoRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))..\</RepoRoot>
    <BaseOutputPath>$(RepoRoot)Artifacts\$(Configuration)\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RepoRoot)Artifacts\$(Configuration)\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
  
</Project>
