<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <AssemblyName>Nivaes.App.Compilers.Toolset</AssemblyName>
    <RootNamespace>Nivaes.App.Compilers.Toolset</RootNamespace>

    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Nivaes.App.Compilers.Toolset</PackageId>
    <Title>Nivaes compilers toolset</Title>

    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <Product>Guid Compiler Toolset</Product>
    <Description>Nivaes compiler toolset.</Description>
    <PackageTags>Nivaes;roslyn</PackageTags>
    <NoPackageAnalysis>true</NoPackageAnalysis>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup>
    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json ;$(RestoreAdditionalProjectSources)</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.7.0-3.final" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.0-beta3.20381.3" PrivateAssets="all" />
  </ItemGroup>

 <ItemGroup>
    <None Update="tools\*.ps1" CopyToOutputDirectory="Always" Pack="true" PackagePath="" />
    <!--<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />-->  
  </ItemGroup>

</Project>
