<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <AssemblyName>Nivaes.Extensions.Candidates</AssemblyName>
    <RootNamespace>Nivaes</RootNamespace>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
