<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <AssemblyName>Nivaes.Extensions.Candidates</AssemblyName>
    <RootNamespace>Nivaes</RootNamespace>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <OptimizationPreference>Speed</OptimizationPreference>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <RunAOTAnalysis>true</RunAOTAnalysis>
    <PublishAot>true</PublishAot>
    <WarningsAsErrors>IL2026;IL3002;IL2028</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" />
    <PackageReference Include="Nivaes.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
