name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  5.0.100-preview.6.20318.15

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    #- name: Test
    #  run: dotnet test --no-restore --verbosity detailed

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: name.zip
        path: ./artifacts/**/*.nupkg

    - name: Publish
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  './Artifacts/**/*.nupkg'
        repo-owner:  'nivaes'
        gh-user:  'andrechi1'
        token:  ${{ secrets.GITHUB_TOKEN }}
      #run: dotnet nuget push './Artifacts/**/*.nupkg'
