name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  5.0.100-preview.6.20318.15

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration release

    #- name: Test
    #  run: dotnet test --no-restore --no-build --configuration release --verbosity normal

    - name: Publish
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  './Artifacts/**/*.nupkg'
        repo-owner:  'nivaes'
        gh-user:  'nivaes'
        token:  ${{ secrets.GITHUB_TOKEN }}
