name: Publish Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build_release:
    uses: Nivaes/Nivaes.Workflows/.github/workflows/basic_lib_publish_release.yaml@develop
    with:
      nuget_source: https://nuget.pkg.github.com/Nivaes/index.json
    secrets:
      nuget_token: ${{ secrets.GITHUB_TOKEN }}
