name: Publish Release

on:
  release:
    types:
      - released
      - prereleased
    #types: [released]
    #types: [prereleased]
    #types: [deleted]

jobs:
  publish_release:

    runs-on: ubuntu-18.04

    steps:

    - name: Get Version
      uses: nivaes/get-version@master
      id: get_version

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: release
      if: github.event.action == 'released'
      run: echo Release

    - name: prereleased
      if: github.event.action == 'prereleased'
      run: echo Prereleased

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20379.13
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release -p:Version=${{ steps.get_version.outputs.version }}

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-build --verbosity normal --output ./Artifacts/ -p:Version=${{ steps.get_version.outputs.version }}

    #- name: Download Release Asset
    #  uses: nivaes/download-release-assets@master
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    #  with:
    #    token: ${{ secrets.DOWNLOAD_TOKEN }}

    - name: Configure nuget
      run: dotnet nuget add source https://nuget.pkg.github.com/Nivaes/index.json --name "github" --username Nivaes --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text

    - name: Publish nuget
      run: dotnet nuget push ./**/*.nupkg --skip-duplicate --source "github"

    #- name: Publish nuget direct
    #  run: dotnet nuget push ./**/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/Nivaes/index.json --username Nivaes --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text

    #- name: Publish packages
    #  run: dotnet nuget push ./**/**.nupkg --skip-duplicate --source https://nuget.pkg.github.com/Nivaes/index.json  --api-key ${{secrets.GITHUB_TOKEN}}

    #- name: Publish packages
    #  run: dotnet nuget push ./**/**.nupkg --skip-duplicate --source https://nuget.pkg.github.com/Nivaes/index.json


    #- name: Publish
    #  uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
    #  with:
    #    nupkg-path:  './**/*.nupkg'
    #    repo-owner:  'Nivaes'
    #    gh-user:  'Nivaes'
    #    token:  ${{ secrets.GITHUB_TOKEN }}

    #- name: Setup .NET Core @ Latest
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: '3.1.102'
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./**/*.nupkg --skip-duplicate --no-symbols true
