name: Publish Release

on:
  release:
    types:
      - released
      - prereleased
    #types: [released]
    #types: [prereleased]
    #types: [deleted]

jobs:
  publish_release:
    runs-on: ubuntu-18.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: release
      if: github.event_name.types == 'released'
      run: echo Release

    - name: release
      if: github.event_name.types == 'prereleased'
      run: echo Prereleased

    - name: Download Release Asset
      uses: nivaes/download-release-assets@master
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish packages
      run: dotnet nuget push ./**/**.nupkg --source https://nuget.pkg.github.com/Nivaes/index.json  --api-key ${{secrets.GITHUB_TOKEN}}
